[project]
name = "LibPyFDP"
version = "0.1.0"
description = "A Python library for DCAT metadata management for Fair Data Points"
authors = [
    { name = "Massimo Gaggero", email = "name dot surname at crs4 dot it" }
]
readme = "README.md"
license = { text = "Apache-2.0" }
requires-python = ">=3.10"
dependencies = [
    "rdflib",
    "requests",
    "SPARQLWrapper"
]

[project.optional-dependencies]
docs = [
    "Sphinx>=7.0",
    "furo",
    "sphinx-copybutton",
    "sphinx-favicon",
    "cloud-sptheme"
]

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"
