name: CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  docs-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install LibPyFDP and dependencies
        run: |
          pip install -e .

      - name: Run tests and generate coverage report
        run: |
          pytest --cov=fdp --cov-report xml:coverage.xml --cov-report html:docs/build/html/coverage-html tests/unit
          COVERAGE=$(python - <<'EOF'
import xml.etree.ElementTree as ET
tree = ET.parse('coverage.xml')
root = tree.getroot()
print(int(float(root.attrib['line-rate'])*100))
EOF
)
          mkdir -p docs/build/html/badges/
          curl -s "https://img.shields.io/badge/coverage-${COVERAGE}%25-brightgreen.svg" -o docs/build/html/badges/coverage.svg
          echo "Coverage badge generated: ${COVERAGE}%"

      - name: Build the site
        run: |
          cd docs
          pip install -r docs-requirements.txt
          make html

      - name: Set up Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'docs/build/html'

  docs-deploy:
    runs-on: ubuntu-latest
    needs: docs-build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        if: github.ref == 'refs/heads/develop'
        uses: actions/deploy-pages@v4
