name: CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

  workflow_dispatch:

jobs:
  unit-test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install LibPyFDP and dependencies
        run: |
          pip install --upgrade pip
          pip install -e .

      - name: Run unittests
        run: |
          pip install -r tests/tests-requirements.txt
          pytest --show-capture=stdout -c tests/pytest.ini tests/unit/ -v
          # pytest --show-capture=stdout --docker-compose-remove-volumes -c libpyfdp/tests/pytest.ini libpyfdp/tests/integration/ -v -s
          pytest --cov=fdp tests/unit
